//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_THWEB_NC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IDOrder { get; set; }
        public string NameUser { get; set; }
        public string Addresss { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<decimal> UnitPriceSale { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string NameProduct { get; set; }
        public Nullable<int> IDProduct { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
